'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
      return queryInterface.bulkInsert('Photos', [
        {userId: 1, title: 'The Ancient Magus\' Bride',imageUrl:'https://upload.wikimedia.org/wikipedia/en/c/c1/The_Ancient_Magus%27_Bride%2C_volume_1.jpg', description: 'Having been ostracized by both her relatives and partially by society, orphaned Japanese high school student Chise Hatori decides to sell herself at an auction in order for somebody else to take her in and have a new place to call home. At the auction in London, she is sold for five million pounds to Elias Ainsworth, a seven-foot-tall humanoid with an animal skull for a head. The magus, who seems closer to a demon than human, either brings her the light she desperately seeks or drowns her in ever deeper shadows in her new country, Great Britain.'},
        {userId: 2, title: 'Deadman Wonderland',imageUrl:'https://upload.wikimedia.org/wikipedia/en/4/44/Deadman_Wonderland_-_Title_Image.jpg', description: 'As an escapee, a survivor of the great earthquake, Ganta has no memories of the tragedy and has lived a normal life. This all changes when a strange person covered in blood and crimson armor floats through his classroom windows. Grinning madly, the "Red Man" massacres Ganta\'s entire class. Instead of killing him, the "Red Man" embeds a red crystal shard in Ganta\'s chest. Within days of the massacre, Ganta is placed on trial as a suspect.'},
        {userId: 3, title: 'Dr. Stone',imageUrl:'https://upload.wikimedia.org/wikipedia/en/2/29/Doctor_stone.jpg', description: 'Beginning in April 5738 AD, it has been over 3,700 years since a mysterious flash petrified nearly all human life. A 15-year-old genius named Senku Ishigami is suddenly revived to find himself in a world where all traces of human civilization have been eroded by time. Senku sets up a base-camp and begins to study the petrified humans in order to determine the cause of the event, as well as a cure.'},
        {userId: 1, title: 'Fire Punch',imageUrl:'https://upload.wikimedia.org/wikipedia/en/3/3b/Firepunch12.jpg', description: 'Fire Punch takes place on an Earth that has become frozen over and barren, purportedly at the hands of a being known as the Ice Witch. The witch is among a few who possess special abilities known as "blessings". The protagonist Agni is a boy who has the blessing of regeneration, along with his sister Luna. They help the few elders in the village subsist on the meat of Agni\'s severed arms. One day, their village is visited by a blessed named Doma who offers to take Agni to his city of Behemdorg. Doma, disgusted at their practice of cannibalism, immolates the inhabitants with his inextinguishable flames. Luna, whose regeneration is slower, also succumbs, but not before imploring Agni to "live".'},
        {userId: 2, title: 'Fist of the North Star',imageUrl:'https://upload.wikimedia.org/wikipedia/en/9/92/Hokuto_no_Ken_tankobon.jpg', description: 'A worldwide nuclear war sometime in the 1990s has resulted in the destruction of most of civilization, turning the world into a desert wasteland. The remnants of mankind fight over whatever supply of food and uncontaminated water still remaining as the strong prey on the weak. Kenshiro is the successor to Hokuto Shinken, an ancient martial art of assassination that trains its practitioners to kill from within an opponent\'s body through the use of hidden meridian points. Kenshiro wishes to live his life in peace, but after he is separated from his fiancée Yuria by a jealous rival, he begins his journey to become the savior of the post-apocalyptic world, defending the weak and innocent from the many organizations that threaten their survival.'},
        {userId: 3, title: 'Gantz',imageUrl:'https://upload.wikimedia.org/wikipedia/en/f/fb/Gantzvol1.jpg', description: 'A pair of high school students, Kei Kurono and Masaru Kato, are hit by a subway train in an attempt to save the life of a drunk homeless man who had fallen onto the tracks. Following their deaths, Kurono and Kato find themselves transported to the interior of an unfurnished Tokyo apartment, where they meet Joichiro Nishi, a Gantz veteran, and other clueless participants. The pair soon realizes that they are not allowed to leave the apartment. At one end of the room there is a large black sphere known as "Gantz".'},
        {userId: 1, title: 'Goblin Slayer',imageUrl:'https://upload.wikimedia.org/wikipedia/en/a/ac/Goblin_Slayer%21%2C_volume_1.jpg', description: 'In a world of fantasy, adventurers come from far and wide to join the Guild. They complete contracts to earn gold and glory. An inexperienced priestess joins her first adventuring party, but comes into danger after her first contract involving goblins goes wrong. As the rest of her party is either wiped out or taken out of commission, she is saved by a man known as Goblin Slayer, an adventurer whose only purpose is the eradication of goblins with extreme prejudice.'},
        {userId: 2, title: 'Hell\'s Paradise: Jigokuraku',imageUrl:'https://upload.wikimedia.org/wikipedia/en/4/4e/Jigokuraku_Vol_1.jpg', description: 'Captured during an assassination mission, Gabimaru is sentenced to be executed, but nothing seems to kill him due to his superhuman body. Believing his love for his wife to be subconsciously keeping him alive, executioner Yamada Asaemon Sagiri offers him the chance to be pardoned of all crimes by the Shogunate if he finds the elixir of life on Shinsenkyo, a legendary realm recently discovered southwest of the Ryukyu Kingdom. After losing five expedition teams sent to the island, this time the Shogunate sends a group of death row convicts. The convicts are each given a Yamada Asaemon executioner, who they must return with in order to obtain the pardon.'},
        {userId: 3, title: 'Jujutsu Kaisen',imageUrl:'https://upload.wikimedia.org/wikipedia/en/4/46/Jujutsu_kaisen.jpg', description: 'Yuji Itadori is an unnaturally fit high school student living in Sendai with his grandfather. He regularly avoids the track team due to the time commitment required for it, despite his innate talent for the sport. Instead, he chooses to join the Occult Research Club; due to the freedom it allows him in attending, he goes to visit his dying grandfather in the hospital every day.'},
        {userId: 1, title: 'My Hero Academia',imageUrl:'https://upload.wikimedia.org/wikipedia/en/f/fb/Gantzvol1.jpg', description: 'The series focuses on Izuku Midoriya, a young man who dreams of becoming a Hero despite being bullied by his violent childhood friend Bakugo for lacking a Quirk. Both youths idolize one of the world\'s greatest heroes All Might. All Might also reveals the nature of his Quirk "One For All" and passes it down to Izuku to succeed him after seeing the youth\'s determination in the face of danger. As Izuku begins his path to becoming a hero in attending U.A. High School alongside Bakugo and the friends they make in Class 1-A, a nemesis to the "One For All" users named All For One conditions his apprentice Tomura Shigaraki to destroy the current society and its heroes.'},
        {userId: 2, title: 'One-Punch Man',imageUrl:'https://upload.wikimedia.org/wikipedia/en/c/c3/OnePunchMan_manga_cover.png', description: 'On a supercontinent Earth, powerful monsters and villains have been wreaking havoc in the cities. In response, the millionaire Agoni creates the Hero Association, which employs superheroes to fight evil. Saitama, an unassociated hero, hails from City Z and performs heroic deeds as a hobby. He has trained himself to the point of being able to defeat any enemy with a single punch, but his unmatched strength has left him with an overwhelming sense of boredom.'},
        {userId: 3, title: 'Plus-Sized Elf',imageUrl:'https://upload.wikimedia.org/wikipedia/en/5/58/Plus-Sized_Elf.jpg', description: 'The series follows human Tomoatsu Naoe, a massage therapist, who helps a chubby elf lose weight so she can be able to return to her home world. Because of this, many other overweight mystical beings come seeking his help.'},
        {userId: 1, title: 'Prison School',imageUrl:'https://upload.wikimedia.org/wikipedia/en/f/f0/Prison_School_Manga_Volume_Cover.png', description: 'Hachimitsu Academy, one of the strictest girls\' academies in Tokyo, has decided to admit boys into their system. Kiyoshi Fujino is one of these new boys, but he discovers to his shock that he and his four friends are the only male students among 1,000 girls. The five boys all commit to voyeurism in the school\'s bathing area with the lecherous philosophy of "all for one, one for all". Their capture and "arrest" by the Underground Student Council causes the five boys to receive an ultimatum: either stay a month in the school\'s Prison Block or be expelled. The boys are incarcerated in the Prison Block together and punishments handed to them by their attractive but vicious supervisors.'},
        {userId: 2, title: 'Shaman King',imageUrl:'https://upload.wikimedia.org/wikipedia/en/9/92/Shaman_King_25.png', description: 'The plot of Shaman King revolves around Yoh Asakura, a shaman, a medium between the worlds of the living and the dead. Yoh seeks to become the Shaman King, the one who is able to contact the Great Spirit, and will gain the ability to reshape the world in any way they wish, and for this purpose, he must win the Shaman Fight, a battle held once every 500 years between competing shamans. Anna Kyoyama, Yoh\'s fiancée, soon enters the scene and prescribes a brutal training regimen to prepare him for the tournament. Thus begins the plot that will lead Yoh on a journey that will lead him to befriend Ryu, Tao Ren, Horohoro, Faust VIII, Lyserg Diethel, and Joco McDonnell'},
        {userId: 3, title: 'Spy × Family',imageUrl:'https://upload.wikimedia.org/wikipedia/en/5/51/Spy_Family_vol_1.jpg', description: 'An action-packed comedy about a fake family that includes a spy, an assassin and a telepath!'},
        {userId: 1, title: 'So I\'m a Spider, So What?',imageUrl:'https://upload.wikimedia.org/wikipedia/en/8/88/So_I%27m_a_Spider%2C_So_What%3F%2C_volume_1.jpg', description: 'In a world where the battle between Hero and Demon Lord repeated itself time and time again, an enormous space-time spell misfired and hit a certain Japanese high school class on Earth, killing everyone in it. However, guided by what seemed to be a miracle, the students were all reincarnated into that other world. While a handful was fortunate enough to become royalty, nobles, and other kinds of influential people, one girl was not so lucky. Being reborn as a spider monster of the weakest kind in a dungeon filled with vicious beasts, she is forced to experience extreme hardship. Even so, armed with nothing but her human knowledge and overwhelming positivity, she continues to press on and survive against creatures much stronger than herself.'},
        {userId: 2, title: 'The Quintessential Quintuplets',imageUrl:'https://upload.wikimedia.org/wikipedia/en/b/ba/The_Quintessential_Quintuplets_volume_1_cover.jpg', description: 'High school student Futaro Uesugi is an academically gifted student that leads a difficult life—his mother has died, he has no friends, and on top of all that, his father has incurred a large amount of debt. An opportunity presents itself when the rich Nakano family transfers to his school. Futaro is promptly hired as a highly paid tutor. However, much to Futaro\'s dismay, he discovers that his five charges—identical quintuplet sisters of varied personalities—have no interest in studying at all and have abysmal grades. Some of the quintuplets are against having Futaro, whom they view as a stranger, in their apartment, but Futaro\'s diligent tenacity gradually convinces those girls to accept him and to improve their grades.'},
        {userId: 3, title: 'Vinland Saga',imageUrl:'https://upload.wikimedia.org/wikipedia/en/5/51/Vinland_Saga_volume_01_cover.jpg', description: 'Vinland Saga is initially set mostly in 1013 AD England, which has been mostly conquered by the Danish King Sweyn Forkbeard. As King Sweyn nears death, his sons, Prince Harald and Prince Canute, are arguing over his succession. The story draws elements from historical accounts of the period such as The Flateyjarbók, The Saga of the Greenlanders and The Saga of Eric the Red.'},
        {userId: 1, title: 'The Way of the Househusband',imageUrl:'https://upload.wikimedia.org/wikipedia/en/f/f7/The_Way_of_the_Househusband.jpg', description: 'Tatsu, an infamous and feared yakuza boss nicknamed "the Immortal Dragon", retires from crime to become a househusband so that he can support Miku, his kyariaūman wife. The episodic series depicts a variety of comedic scenarios, typically wherein Tatsu\'s banal domestic work as a househusband is juxtaposed against his intimidating personality and appearance, and his frequent run-ins with former yakuza associates and rivals.'},
      ], {});
  },

  down: (queryInterface, Sequelize) => {
      return queryInterface.bulkDelete('Photos', null, {});

  }
};
