'use strict';

module.exports = {
  up: (queryInterface, Sequelize) => {
     return queryInterface.bulkInsert('Comments', [
       {userId: 1, photoId: 5, content:"This was a great read."},
       {userId: 1, photoId: 6, content:"A very good story!"},
       {userId: 1, photoId: 7, content:"The story was incredible!"},
       {userId: 1, photoId: 8, content:"The art is so good!"},
       {userId: 1, photoId: 9, content:"I can’t wait to read more."},
       {userId: 1, photoId: 10, content:"This was a great read."},
       {userId: 1, photoId: 11, content:"A very good story!"},
       {userId: 1, photoId: 12, content:"The story was incredible!"},
       {userId: 1, photoId: 13, content:"The art is so good!"},
       {userId: 1, photoId: 14, content:"I can’t wait to read more."},
       {userId: 1, photoId: 15, content:"This was a great read."},
       {userId: 1, photoId: 16, content:"A very good story!"},
       {userId: 1, photoId: 17, content:"The story was incredible!"},
       {userId: 1, photoId: 18, content:"The art is so good!"},
       {userId: 1, photoId: 19, content:"I can’t wait to read more."},
       {userId: 1, photoId: 1, content:"This was a great read."},
       {userId: 1, photoId: 2, content:"A very good story!"},
       {userId: 1, photoId: 3, content:"The story was incredible!"},
       {userId: 1, photoId: 4, content:"The art is so good!"},
       {userId: 2, photoId: 10, content:"This was a great read."},
       {userId: 2, photoId: 12, content:"A very good story!"},
       {userId: 2, photoId: 13, content:"The story was incredible!"},
       {userId: 2, photoId: 14, content:"The art is so good!"},
       {userId: 2, photoId: 15, content:"I can’t wait to read more."},
       {userId: 2, photoId: 16, content:"This was a great read."},
       {userId: 2, photoId: 17, content:"A very good story!"},
       {userId: 2, photoId: 18, content:"The story was incredible!"},
       {userId: 2, photoId: 19, content:"The art is so good!"},
       {userId: 2, photoId: 1, content:"I can’t wait to read more."},
       {userId: 2, photoId: 2, content:"This was a great read."},
       {userId: 2, photoId: 3, content:"A very good story!"},
       {userId: 2, photoId: 4, content:"The story was incredible!"},
       {userId: 2, photoId: 5, content:"The art is so good!"},
       {userId: 2, photoId: 6, content:"I can’t wait to read more."},
       {userId: 2, photoId: 7, content:"This was a great read."},
       {userId: 2, photoId: 8, content:"A very good story!"},
       {userId: 2, photoId: 9, content:"The story was incredible!"},
       {userId: 2, photoId: 11, content:"The art is so good!"},
       {userId: 3, photoId: 15, content:"This was a great read."},
       {userId: 3, photoId: 16, content:"A very good story!"},
       {userId: 3, photoId: 17, content:"The story was incredible!"},
       {userId: 3, photoId: 18, content:"The art is so good!"},
       {userId: 3, photoId: 19, content:"I can’t wait to read more."},
       {userId: 3, photoId: 1, content:"This was a great read."},
       {userId: 3, photoId: 2, content:"A very good story!"},
       {userId: 3, photoId: 3, content:"The story was incredible!"},
       {userId: 3, photoId: 4, content:"The art is so good!"},
       {userId: 3, photoId: 5, content:"I can’t wait to read more."},
       {userId: 3, photoId: 6, content:"This was a great read."},
       {userId: 3, photoId: 7, content:"A very good story!"},
       {userId: 3, photoId: 8, content:"The story was incredible!"},
       {userId: 3, photoId: 9, content:"The art is so good!"},
       {userId: 3, photoId: 10, content:"I can’t wait to read more."},
       {userId: 3, photoId: 11, content:"This was a great read."},
       {userId: 3, photoId: 12, content:"A very good story!"},
       {userId: 3, photoId: 13, content:"The story was incredible!"},
       {userId: 3, photoId: 14, content:"The art is so good!"},
     ], {});
    },

  down: (queryInterface, Sequelize) => {
   return queryInterface.bulkDelete('Comments', null, {});
  }
};
